sonar.projectKey = Project_P1
sonar.host.url = http://localhost:9000
sonar.organization = Atharva-70

sonar.sources = .
sonar.exclusions = venv/**, pycache/**, **/__pycache__/**, tests/**, .env, kubernetes/**

sonar.python.version = 3.12